U of T DSI algorithms and data structures: Assignment 1
ishrathmi/algorithms_and_data_structures pull request #1
Opened 2024-11-14 23:55 UTC by ishrathmi

## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
set up a function to find missing numbers in a list

## What did you learn from the changes you have made?
how to write a linear search function and propose an alternative solution, how to evaluate space and time complexity of a function

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
a recursive function instead of linear search

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
I googled help with coding errors and understanding time and space complexity

## How were these changes tested?
by running the code

## A reference to a related issue in your repository (if applicable)
n/a

## Checklist
- [ ] I can confirm that my changes are working as intended

2024-11-17 01:29 UTC, tianyi21 requested changes
Hi Ishrath! 

Thank you for completing and submitting your ADS A1:
* You implemented an algorithm to identify the missing number in a provided list.
* You demonstrated how you approached the problem and analyzed your solution.

I noticed the following issue(s) with your submission. I would be appreciate if you could provide a short explanation and revise your submission to address these issue(s):
* You stated that the time complexity of your solution is $O(n)$. However, in your solution, `if x not in nums` iterates through the whole list without an explicit `for` loop. Therefore, could you re-consider what would be the time complexity of your current solution?
* You created a list named `list1` and appended missing elements to the list. Is the space complexity still $O(1)$?
* Can you derive a more efficient algorithm by utilizing one of the data structures introduced during the live learning session? Hint: you only need one additional line.

Thanks,
Tianyi [LS]

2024-11-17 19:58 UTC, ishrathmi commented
Hi Tianyi, 

thanks for the feedback. 

1. The time complexity should be O(1) as it is one list and any new elements are simply being appended to it.
2. the space complexity should be O(n)
3.  I am unsure how to amend the code I have already written. what I can think of is to convert everything to a set and find the difference between the input and a set in range 0,n. 

Thanks,
Ishrath

2024-11-17 20:13 UTC, tianyi21 commented
Hi Ishrath,

Thank you for your updates.
1. there are essentially two `for` loop in your code: `for x in range(0, max)`: is the first one, and `if x not in nums` is the second one. As I suggested before, since here `nums` is a list, it iterates through the whole list, which give $O(n^2)$ instead of $O(n)$ as stated in your submission and $O(1)$ in your comment above.
2. This is correct.
3. Yes, convert a list into a set can significantly improve the `if x not in nums`, since python `set` use a hash map backend and `in` set takes constant time compared with `in` list takes linear time. You can try to compare the following two code pieces.

```
import time
def missing_num1(nums: list[int]) ->int:
    max = nums[0]
    for i in nums:
        if i > max:
            max = i

    list1 = []

    for x in range (0, max):
        if x not in nums:
            list1.append(x)

    return list1

def missing_num2(nums: list[int]) ->int:
    max = nums[0]
    for i in nums:
        if i > max:
            max = i

    list1 = []
    #convert list to set
    nums = set(nums)
    for x in range (0, max):
        if x not in nums:
            list1.append(x)

    return list1

tic = time.time()
missing_num1(list(range(int(1e5))))
toc = time.time()
toc - tic

tic = time.time()
missing_num2(list(range(int(1e5))))
toc = time.time()
toc - tic
```

Does my comment above make sense to you? Feel free to leave a comment if you find anything confusing.

Thanks,
Tianyi [LS]

2024-11-25 17:18 UTC, ishrathmi commented
Thanks Tianyi! I see, I forgot to take python backend operations into account. So just converting the elements to a list alone can improve performance. I thought I had to redo the whole approach in a set.

Ok I need to look more into defining the time and space complexity, since it seems I find it difficult to understand. Thanks for the feedback!

2024-11-25 17:21 UTC, tianyi21 approved these changes
Hi Ishrath!

All your ADS assignments have been completed. Thank you for your participation, and I wish you all the success in your future endeavours.

Thanks,
Tianyi [LS]

2025-01-13 09:30 UTC, closed without merging